In [1]:
import numpy as np 
import pandas as pd
from matplotlib.animation import FuncAnimation
import matplotlib as plt
from IPython.display import display, Math
from sympy import *
import sympy 
import matplotlib.pyplot as plt
from sympy import symbols 
from sympy.solvers import solve 
from matplotlib.patches import Polygon
from matplotlib.colors import LogNorm
plt.rcParams['font.sans-serif'] = ['Microsoft YaHei']
plt.rcParams['axes.unicode_minus'] = False
import ipywidgets as wg
import random
from matplotlib.patches import Ellipse
from matplotlib.text import OffsetFrom
from io import StringIO
from tqdm import tqdm,trange  # loop  for dog in  tqdm(dogs): for dog in  trange(6)
from time import sleep
from datetime import datetime
import sklearn
import matplotlib.patches as mpatches
import matplotlib.image as mpimg
import math
%matplotlib inline
from functools import reduce
import seaborn as sns
import matplotlib as mpl
from statsmodels.stats import weightstats   # weightstats =for t and z test 
import statsmodels.stats.proportion as propotion # 2 proportions -
from statsmodels.stats import proportion
from scipy.stats import norm 
import scipy.stats as stats
plt.rcParams['font.sans-serif'] = ['SimHei'] 
plt.rcParams['axes.unicode_minus'] = False 
import cmath
from itertools import combinations
from itertools import permutations
from matplotlib import *
from matplotlib.patches import Rectangle
from matplotlib.patches import Circle
from matplotlib.patches import Polygon

In [2]:
circlesin=pd.read_csv("circlesin.csv")

In [3]:
circlesin.info()

<class 'pandas.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       63 non-null     float64
 1   0       63 non-null     float64
dtypes: float64(2)
memory usage: 1.1 KB

In [4]:
circlesin.describe()

               1          0
count  63.000000  63.000000
mean    0.002666   0.000156
std     0.713727   0.711840
min    -0.999135  -0.999923
25%    -0.696104  -0.696653
50%    -0.012389   0.016814
75%     0.702688   0.696410
max     0.999859   0.999574

In [5]:
circlesin.head()

          1         0
0  0.995004  0.099833
1  0.980067  0.198669
2  0.955336  0.295520
3  0.921061  0.389418
4  0.877583  0.479426

In [6]:
circlesin.columns=['x-cos','y-sin']

In [7]:
circlesin.columns

Index(['x-cos', 'y-sin'], dtype='str')

In [8]:
circlesin.head()

      x-cos     y-sin
0  0.995004  0.099833
1  0.980067  0.198669
2  0.955336  0.295520
3  0.921061  0.389418
4  0.877583  0.479426

In [ ]:
sns.relplot(circlesin)
plt.savefig('circlesin.',dpi=5000)
plt.show()

In [ ]:
sns.relplot(circlesin,x='x-cos', y='y-sin')
plt.show()